PPM_elaborato_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('music/', include('music.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'music'

urlpatterns = [
    path('playlist/<int:playlist_id>/', views.playlist, name="playlist"),
    path('createPlaylist', views.createPlaylist, name='createPlaylist'),
    path('searchResults/', views.search_results, name="search_results"),
    path('allsongs/', views.all_songs, name="allsongs"),
    path('deletePlaylist', views.deletePlaylist, name="deletePlaylist"),
    path('addSongToPlaylist', views.addSongToPlaylist, name="addSongToPlaylist"),
    path('modify_playlist_image/<int:playlist_id>', views.modify_playlist_image, name='modify_playlist_image'),
    path('likedsongs/', views.likedsongs, name="likedsongs"),
    path('likesong', views.likesong, name="likesong"),
    path('add-song', views.add_song, name='add_song'),
    path('delete_song_from_playlist', views.delete_song_from_playlist, name="delete_song_from_playlist"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import FileExtensionValidator
from django import forms


# Create your models here.


class Song(models.Model):
    song_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    artist = models.CharField(max_length=50)
    album = models.CharField(max_length=50, blank=True)
    GENRE_CHOICES = [
        ('rock', 'Rock'),
        ('pop', 'Pop'),
        ('hiphop', 'Hip Hop'),
        ('jazz', 'Jazz'),
        ('electronic', 'Electronic'),
        ('classical', 'Classical'),
        ('latin', 'Latin'),
        ('other', 'Other'),
    ]
    genre = models.CharField(max_length=20, blank=True, default='genre', choices=GENRE_CHOICES)
    song = models.FileField(upload_to="songs/", validators=[FileExtensionValidator(allowed_extensions=['mp3', 'wav'])], default="name")
    image = models.ImageField(upload_to="songimage/", validators=[FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])])
    data = models.DateTimeField(auto_now=False, auto_now_add=True)
    slug = models.SlugField()
    liked_by_users = models.ManyToManyField(User, related_name="liked_songs", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Playlist(models.Model):
    playlist_id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    playlist_name = models.CharField(max_length=50, default="name")
    image = models.ImageField(upload_to="playlist_images/", validators=[FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'png'])], blank=True)
    plays = models.IntegerField(default=0)
    songs = models.ManyToManyField(Song, related_name='playlist')
    slug = models.SlugField()

    def __str__(self):
        return self.playlist_name

music/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import Song, Playlist


def playlist(request, playlist_id):
    user = request.user
    if user.is_authenticated:
        myPlaylists = Playlist.objects.filter(user=user)
        if request.method == "POST":
            song_id = request.POST["music_id"]
            playlist = Playlist.objects.filter(playlist_id=playlist_id).first()
            if song_id in playlist.songs.all():
                playlist.songs.remove(song_id)
                playlist.plays -= 1
                playlist.save()
        else:
            currPlaylist = Playlist.objects.filter(playlist_id=playlist_id).first()
            playlistSongs = currPlaylist.songs.all()
            recommendedSingers = []
            return render(request, "music/playlist.html", {'playlistInfo': currPlaylist,
                                                           'playlistSongs': playlistSongs,
                                                           'myPlaylists': myPlaylists,
                                                           'recommendedSingers': recommendedSingers})


def createPlaylist(request):
    user = request.user
    if(user.is_authenticated):
        playlist_name = request.POST["playlist_name"]
        print(f"User: {user}")
        print(f"Playlist Name: {playlist_name}")
        image = request.FILES.get("image")
        newplaylist = Playlist(user=user, playlist_name=playlist_name, image=image)
        newplaylist.save()
        return redirect("music:playlist", playlist_id=newplaylist.playlist_id)
    else:
        return redirect("users:login")


def all_songs(request):
    user = request.user
    genre = request.GET.get('genre')
    if genre:
        allsongs = Song.objects.filter(genre=genre)
    else:
        allsongs = Song.objects.all()
    genres = Song.GENRE_CHOICES
    if user.is_authenticated:
        all_liked = request.user.liked_songs.all()
        my_playlists = Playlist.objects.filter(user=user)
        return render(request, 'music/allsongs.html', {'allsongs': allsongs, 'my_playlists': my_playlists, 'genres': genres, 'all_liked': all_liked})
    else:
        return render(request, 'music/allsongs.html', {'allsongs': allsongs, 'genres': genres})


def search_results(request):
    user = request.user
    myPlaylists = []
    if user.is_authenticated:
        myPlaylists = list(Playlist.objects.filter(user=user))
        all_liked = request.user.liked_songs.all()
    if request.method == "POST":
        data = request.POST["data"]
        songsFound = Song.objects.filter(name__icontains=data)
        playlistsFound = Playlist.objects.filter(playlist_name__icontains=data)
        songsFound = list(songsFound)[:6]
        if not user.is_authenticated:
            return render(request, 'music/searchResults.html',{'songsFound': songsFound})
        else:
            return render(request, 'music/searchResults.html',
                          {'songsFound': songsFound, 'playlistsFound': playlistsFound, 'all_liked': all_liked, 'myPlaylists': myPlaylists})
    else:
        return redirect('/')


def deletePlaylist(request):
    if request.method == "POST":
        playlist_id = request.POST["playlist_id"]
        Playlist.objects.filter(playlist_id=playlist_id).delete()
    return redirect("/")


def addSongToPlaylist(request):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            song_id = request.POST.get('song_id')
            playlist_id = request.POST.get('playlist_id')
            if song_id and playlist_id:
                song = Song.objects.get(song_id=song_id)
                playlist = Playlist.objects.get(playlist_id=playlist_id)
                if song not in playlist.songs.all():
                    playlist.songs.add(song)
                    playlist.plays = playlist.songs.count()
                    playlist.save()
        return redirect('homepage')


def delete_song_from_playlist(request):
    if request.method == 'POST':
        song_id = request.POST.get('song_id')
        playlist_id = request.POST.get('playlist_id')
        if song_id and playlist_id:
            playlist = get_object_or_404(Playlist, pk=playlist_id)
            song = get_object_or_404(Song, pk=song_id)
            playlist.songs.remove(song)
            playlist.plays = playlist.songs.count()
            playlist.save()
        return redirect('music:playlist', playlist_id=playlist_id)
    return redirect('music:playlist')


def modify_playlist_image(request, playlist_id):
    if request.method == 'POST':
        playlist = get_object_or_404(Playlist, playlist_id=playlist_id)
        if 'image' in request.FILES:
            playlist.image = request.FILES['image']
            playlist.save()
    return redirect('music:playlist', playlist_id=playlist_id)


def add_song(request):
    if request.method == 'POST':
        name = request.POST["name"]
        artist = request.POST["artist"]
        song = request.FILES.get("song")
        genre = request.POST.get("genre")
        image = request.FILES.get("image")
        newsong = Song(name=name, artist=artist, song=song, image=image, genre=genre)
        newsong.save()
        return redirect("homepage")


def likedsongs(request):
    user = request.user
    if user.is_authenticated:
        all_liked = request.user.liked_songs.all()
        return render(request, 'music/likedsongs.html', {'all_liked': all_liked})


def likesong(request):
    user = request.user
    if user.is_authenticated:
        if request.method == "POST":
            song_id = request.POST.get('song_id')
            state = request.POST.get('state')
            song = get_object_or_404(Song, song_id=song_id)
            if state == 'liked':
                if song.liked_by_users.filter(id=user.id).exists():
                    user.liked_songs.remove(song)
            else:
                user.liked_songs.add(song)
            return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

music/templates/music/allsongs.html
{% extends 'layout.html' %}

{% block title %}
    All songs list
{% endblock %}

{% block main-content %}
    <h2 style="text-align: center; margin: 10px 0; font-size: 3rem">All Songs</h2>
    <form style="right:50px; top: 120px; position: absolute" method="GET">
        <label for="genre">Filter by genre:</label>
        <select name="genre" id="genre">
            <option value="">All genres</option>
            {% for value, display in genres %}
                <option value="{{ value }}" {% if value == request.GET.genre %}selected{% endif %}>{{ display }}</option>
            {% endfor %}
        </select>
        <button type="submit">Filter</button>
    </form>
    {% if allsongs %}
        <p style="margin-left: 25px">There are {{ allsongs|length }} songs:</p>
    {% else %}
        <p>No songs found.</p>
    {% endif %}
        <div id="songlist">
        {% for i in allsongs %}
            <div class="sameMovieCard">
                <div class="container_songpost">
                    <img src="{{i.image.url}}" id="A_{{i.song_id}}"/>
                    <div class="overlay_songpost"></div>
                    <div class="play-btn_songpost">
                        <a class="play-btn" data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)"><i class="fa-solid fa-circle-play"></i></a>
                    </div>
                </div>
                <div class="songpost_data">
                    <h5 class="song-name" id="B_{{i.song_id}}"><a data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)">{{i.name}}</a></h5>
                    <p class="singer-name" id="C_{{i.song_id}}">{{i.artist}}</p>
                    {% if user.is_authenticated %}
                        <a class="add-playlist-btn-allSongs" id="{{i.song_id}}" onclick="showDiv(this)" title="Add to Playlist"> <i class="fas fa-ellipsis-h"></i></a>
                        <form id="my_form" action="{% url 'music:likesong' %}" method="post" style="margin:0">
                            {% csrf_token %}
                            <input type="hidden" id="helo" name="song_id" value="{{i.song_id}}">
                            <input type="hidden" id="state" name="state" value="{% if i in all_liked %}liked{%else%}{% endif %}">
                            <button type="submit" id="submitremove" style="color: red; margin-top: 15px;">
                                <a id="likeButton" class="{% if i in all_liked %}fa-solid {% else %}fa-regular {% endif %}fa-heart" data-song-id="{{i.song_id}}" style="color: black; margin-bottom:20px;" onclick="toggleHeart(this)"></a>
                            </button>
                        </form>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <br>
        <br>
        </div>

        <div id="divId">
            {% if my_playlists %}
                <label for="playlist_{{ song.song_id }}" style="margin: 5px; font-size: 0.75rem; font-weight: 700; color: rgb(138, 138, 138); text-align: left;">Add This Song To Your Playlist</label>
                <form style="margin:0;" id="my_form" action="{% url 'music:addSongToPlaylist' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="song_id" id="song_id">
                    <select name="playlist_id" id="playlist_id">
                    {% for playlist in my_playlists %}
                        <option value="{{playlist.playlist_id}}" class="left-panel-btn" style="margin:0;">{{playlist.playlist_name}}</option><br>
                    {% endfor %}
                    </select>
                    <button class="submitb" type="submit">Add to Playlist</button>
                </form>
            {% else %}
                <p style="margin: 5px; font-size: 0.8rem; font-weight: 700; color: rgb(138, 138, 138); text-align: left;">You don't have any Playlist.</p>
                <a class="create-p" onclick="$('#divId').css({display: 'none'}); document.getElementById('modal-wrapper-playlist').style.display='block'"><i class="fas fa-plus"></i> Create Playlist</a>
            {% endif %}
        </div>

    <script>
        function toggleHeart(element) {
        e.preventDefault();
        var songId = element.getAttribute('data-song-id');
        var stateElement = document.getElementById('state').value;
        var currentState = stateElement.value;
        var newState = currentState === 'liked' ? '' : 'liked';

        stateElement.value = newState;
        if (newState === 'liked') {
            document.getElementById('likeButton').classList.add('liked' , 'fas', 'heart-red');
        } else {
            document.getElementById('likeButton').classList.remove('liked');
            document.getElementById('likeButton').classList.add('fa-regular');
        }
        document.getElementById('my_form').submit();
    }


        <!--function toggleHeart(element) {
            if (element.classList.contains('fa-regular')) {
                element.classList.remove('fa-regular');
                element.classList.add('fas', 'heart-red');
            } else {
                element.classList.remove('fas', 'heart-red');
                element.classList.add('fa-regular');
            }
        } -->

    </script>
{% endblock %}

music/templates/music/example.html
{% extends 'layout.html' %}
{% block main-content %}
    <li>this atleast must show</li>
        {% for song in songs %}
            <li>{{ song }}</li>
        {% empty %}
            <li>Oops! I have nothing in the database :(</li>
        {% endfor %}
    {% for i in songs %}
        <div class="carousel-cell">
            <section class="main_song">
                <div class="song-card">
                    <div class="containera">
                        <img src="{{i.image}}" id="A_{{i.id}}" alt="song cover">
                        <div class="overlaya"></div>
                        <div>
                            <a class="play-btn" href="{{i.preview_url}}" id="{{i.id}}"><i class="fas fa-play-circle"></i></a>
                            {% if user.is_authenticated %}
                                <div class="add-playlist-btn">
                                    <a id="W_{{i.song_id}}" title="Add to Playlist" onclick="showDiv(this)"></a>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div>
                    <p class="songName" id="B_{{i.id}}">{{i.name}}</p>
                </div>
                <p class="artistName">{{i.singer1}}</p>
            </section>
        </div>
    {% endfor %}
{% endblock %}

music/templates/music/likedsongs.html
{% extends 'layout.html' %}


{% block title %}
    Liked Songs
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
{% endblock %}

{% block main-content %}

    <div id="body-center">
        <div class="card">
            <img  style="background-color: #bc0802; border: 2px solid black" src="/media/images/heart-small.png" width="250px" height="250px">
            <div class="cardData">
                <h1 style="background-color: #bc0802; border-radius: 10px; padding:0 10px">LIKED SONGS <i class="fa-regular fa-heart"></i></h1>
                <p>{{all_liked|length}} liked Songs:</p>
                <br>
                <a href="{% url 'music:allsongs' %}" id="add_song_btn"><i class="fas fa-plus"></i>Add Song</a>
            </div>
        </div>

        {% if all_liked %}
        <h2 id="your-song">There are {{ all_liked|length }} liked songs:</h2>
        <div id="songlist">
            {% for i in all_liked %}
                <div class="sameMovieCard">
                    <div class="container_songpost">
                        <img src="{{i.image.url}}" id="A_{{i.song_id}}"/>
                        <div class="overlay_songpost"></div>
                        <div class="play-btn_songpost">
                            <a class="play-btn" data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)"><i class="fa-solid fa-circle-play"></i></a>
                        </div>
                    </div>
                    <div class="songpost_data">
                        <h5 class="song-name" id="B_{{i.song_id}}"><a data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)">{{i.name}}</a></h5>
                        <p class="singer-name" id="C_{{i.song_id}}">{{i.artist}}</p>
                        <form id="delform" action="{% url 'music:likesong' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="song_id" value="{{ i.song_id }}">
                            <input type="hidden" id="state" name="state" value="liked">
                            <button type="submit" id="submitremove" style="color: red; margin-top: 15px; margin-left: 200px" onclick="removeSongFromLiked(this)">
                                <i style="margin-top: 10px" class="fa-solid fa-ban"></i>
                            </button>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% else %}
        <h2 style="margin-bottom: 40px">Currently you have 0 Liked Songs</h2>
        {% endif %}

        <div id="footer"></div>
    <br>
    <br>
    <br>
    </div>

    <script>
    document.getElementById('likeButton').addEventListener('click', function(e) {
        var currentState = document.getElementById('state').value;
        if(currentState == 'liked')
            currentState = 'nolike';
        else
            currentState = 'liked';
        document.getElementById('state').value = currentState;
        $.ajax({
                "url": "/likedsongs/",
                "type": "post",
                "data": { 'song_id' : song_id, 'csrfmiddlewaretoken': '{{ csrf_token }}', 'state' : currentState},
        })
        document.getElementById('submitremove').submit();})

    </script>
{% endblock %}

music/templates/music/playlist.html
{% extends 'layout.html' %}


{% block title %}
    {{ playlistInfo.playlist_name }}
{% endblock %}


{% block main-content %}
    <div id="body-center">
        <div class="card">
            <div>
                <img src="{% if playlistInfo.image %}{{ playlistInfo.image.url }}{% else %}/media/images/music-placeholder.png{% endif %}" alt="No Image Found">
                <a id="modify_image_link" style=" color:white; display:block; margin-left: 100px; font-size:1rem" onclick="showImageForm()"><u>Modify Playlist Image</u></a>
            </div>
            <div class="cardData">
                <h1 id="B_{{playlistInfo.playlist_id}}">{{playlistInfo.playlist_name}}</h1>
                <p>{{playlistInfo.plays}} Songs</p>
                <br>
                <a id="add_song_btn" href={% url 'music:allsongs' %}><i class="fas fa-plus"></i>Add Song</a>
            </div>
        </div>
        <h2 id="your-song">Your Songs:</h2>
        {% if playlistSongs %}
            <div id="songlist">
                {% for i in playlistSongs %}
                    <div class="sameMovieCard">
                        <div class="container_songpost">
                            <img src="{{i.image.url}}" id="A_{{i.song_id}}"/>
                            <div class="overlay_songpost"></div>
                            <div class="play-btn_songpost">
                                <a class="play-btn" data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)"><i class="fa-solid fa-circle-play"></i></a>
                            </div>
                        </div>
                        <div class="songpost_data">
                            <h5 class="song-name" id="B_{{i.song_id}}"><a data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)">{{i.name}}</a></h5>
                            <p class="singer-name" id="C_{{i.song_id}}">{{i.artist}}</p>
                            <form action="{% url 'music:delete_song_from_playlist' %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="song_id" value="{{ i.song_id }}">
                                <input type="hidden" name="playlist_id" value="{{ playlistInfo.playlist_id }}">
                                <button type="submit" id="submitremove" style="color: red; margin-top: 15px; margin-left: 200px">
                                    <i style="margin-top:10px" class="fa-solid fa-ban"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h2 id="no-song">Currently No Songs Added in Your Playlist "{{ playlistInfo.playlist_name }}"</h2>
        {% endif %}


        <div id="imageForm" style="display: none;">
            <form action="{% url 'music:modify_playlist_image' playlistInfo.playlist_id %}" method="POST" enctype="multipart/form-data">
                <h2>Change Playlist Image</h2>
                {% csrf_token %}
                <input type="file" name="image" accept="image/*" required>
                <button type="submit">Upload Image</button>
            </form>
        </div>

        <div>
            <form action="{% url 'music:deletePlaylist' %}" method="POST">{% csrf_token %}
                <input type="hidden" name="playlist_id" value="{{playlistInfo.playlist_id}}">
                <button id="delete-btn" type="submit">Delete Playlist</button>
            </form>
        </div>

        <div id="footer"></div>
    </div>


    <script>

        function showImageForm() {
            var form = document.getElementById('imageForm');
            form.style.display = 'block';
            document.addEventListener('mouseup', function(event) {
                var container = document.getElementById('imageForm');
                if (!container.contains(event.target)) {
                    container.style.display = 'none';
            }
            }, { once: true });
        }

    </script>
{% endblock %}

music/templates/music/searchResults.html
{% extends 'layout.html' %}


{% block title %}
    Search Results
{% endblock %}

{% block main-content %}

    {% if songsFound %}
        <h2 style="text-align: center; margin: 10px 0; font-size: 3rem">Songs Found:</h2>
            <div id="songlist">
            <p style="margin-left: 25px">{{ songsFound|length }} songs found:</p>
                {% for i in songsFound %}
                    <div class="sameMovieCard">
                        <div class="container_songpost">
                            <img src="{{i.image.url}}" id="A_{{i.song_id}}" />
                            <div class="overlay_songpost"></div>
                            <div class="play-btn_songpost">
                                <li><a class="play-btn" data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)"><i class="far fa-play-circle fa-2x"></i></a>
                                </li>
                            </div>
                        </div>
                        <div class="songpost_data">
                            <h5 class="song-name" id="B_{{i.song_id}}"><a data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)">{{i.name}}</a></h5>
                    <p class="singer-name" id="C_{{i.song_id}}">{{i.artist}}</p>
                    {% if user.is_authenticated %}
                        <a class="add-playlist-btn-allSongs" id="{{i.song_id}}" onclick="showDiv(this)" title="Add to Playlist"> <i class="fas fa-ellipsis-h"></i></a>
                        <form id="my_form" action="{% url 'music:likesong' %}" method="post" style="margin:0">
                            {% csrf_token %}
                            <input type="hidden" id="helo" name="song_id" value="{{i.song_id}}">
                            <input type="hidden" id="state" name="state" value="{% if i in all_liked %}liked{%else%}{% endif %}">
                            <button type="submit" id="submitremove" style="color: red; margin-top: 15px;">
                                <a id="likeButton" class="{% if i in all_liked %}fa-solid {% else %}fa-regular {% endif %}fa-heart" data-song-id="{{i.song_id}}" style="color: black; margin-bottom:20px;" onclick="toggleHeart(this)"></a>
                            </button>
                        </form>
                    {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
    {% else %}
            <h2 style="text-align: center; margin: 10px 0; font-size: 3rem">Songs Found:</h2>
            <p style="margin-left: 25px; text-align: center; margin-top:100px;">NO SONGS FOUND</p>
    {% endif %}

{% if user.is_authenticated %}
    {% if playlistsFound %}
        <h2 style="text-align: center; margin: 10px 0; font-size: 3rem">Playlist Found:</h2>
        <p style="margin-left: 25px">{{ playlistsFound|length }} playlists found:</p>
        <div class="main_content">
            {% for i in playlistsFound %}
                <section class="main_song">
                    <a href="{% url 'music:playlist' i.playlist_id %}"><img style="border-radius: 4%" src="{% if i.image %}{{ i.image.url }}{% else %}/media/images/music-placeholder.png{% endif %}" alt="playlist image"></a>
                    <a class="playlist-title" href="{% url 'music:playlist' i.playlist_id %}">{{ i.playlist_name }}</a>
                </section>
            {% endfor %}
        </div>
    {% else %}
        <h2 style="text-align: center; margin: 10px 0; font-size: 3rem">Playlists Found:</h2>
        <p style="margin-left: 25px; text-align: center; margin-top:100px;">NO PLAYLISTS FOUND</p>
    {% endif %}
{% endif %}

    <div id="divId">
        {% if myPlaylists %}
            <label for="playlist_{{ song.song_id }}" style="margin: 5px; font-size: 0.75rem; font-weight: 700; color: rgb(138, 138, 138); text-align: left;">Add This Song To Your Playlist</label>
            <form style="margin:0;" id="my_form" action="{% url 'music:addSongToPlaylist' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="song_id" id="song_id">
                <select name="playlist_id" id="playlist_id">
                    {% for playlist in myPlaylists %}
                        <option value="{{playlist.playlist_id}}" class="left-panel-btn" style="margin:0;">{{playlist.playlist_name}}</option><br>
                    {% endfor %}
                </select>
                <button class="submitb" type="submit">Add to Playlist</button>
            </form>
        {% else %}
            <p style="margin: 5px; font-size: 0.8rem; font-weight: 700; color: rgb(138, 138, 138); text-align: left;">You don't have any Playlist.</p>
            <a class="create-p" onclick="$('#divId').css({display: 'none'}); document.getElementById('modal-wrapper-playlist').style.display='block'"><i class="fas fa-plus"></i> Create Playlist</a>
        {% endif %}
    </div>
    <br>
    <br>
    <br>


{% endblock %}