PPM_elaborato_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('music/', include('music.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'music'

urlpatterns = [
    path('playlist/<int:playlist_id>/', views.playlist, name="playlist"),
    path('createPlaylist', views.createPlaylist, name='createPlaylist'),
    path('searchResults/', views.search_results, name="search_results"),
    path('allsongs/', views.all_songs, name="allsongs"),
    path('deletePlaylist', views.deletePlaylist, name="deletePlaylist"),
    path('addSongToPlaylist', views.addSongToPlaylist, name="addSongToPlaylist"),
    path('modify_playlist_image/<int:playlist_id>', views.modify_playlist_image, name='modify_playlist_image'),
    path('likedsongs/', views.likedsongs, name="likedsongs"),
    path('likesong', views.likesong, name="likesong"),
    path('add-song', views.add_song, name='add_song'),
    path('delete_song_from_playlist', views.delete_song_from_playlist, name="delete_song_from_playlist"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout, name="logout"),
]

users/models.py
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django import forms


class UserCreateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(UserCreateForm, self).__init__(*args, **kwargs)

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import auth
from django.contrib import messages
from django.contrib.auth import login
from . import models


# Create your views here.


def register_view(request):
    if request.method == "POST":
        form = models.UserCreateForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('homepage')
    else:
        form = models.UserCreateForm()
    return render(request, "users/register.html", {"form": form})


def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('homepage')
    else:
        form = AuthenticationForm()
    return render(request, "users/login.html", {"form": form})


def logout_view(request):
    try:
        auth.logout(request)
        messages.info(request,"User Logged Out!")
        return redirect('/')
    except:
        return redirect("/")


def logout(request):
    try:
        auth.logout(request)
        messages.info(request,"User Logged Out!")
        return redirect('/')
    except:
        return redirect("/")

users/templates/users/login.html
{% extends 'layout_users.html' %}


{% block title %}
    USERS LOGIN
{% endblock %}


{% block main-content %}
    <div class="login-form">
        <p><b>USER LOGIN</b></p>
        <form class="form-with-validation" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Submit</button>
        </form>
    </div>

    <div class="reg">
        <p> OR SIGN IN <a href="{% url 'users:register' %}"><u>CLICKING HERE!</u></a></p>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'layout_users.html' %}


{% block title %}
    USERS REGISTRATION
{% endblock %}

{% block main-content %}
    <div class="register-form">
        <p>REGISTER A NEW USER</p>
        <form class="form-with-validation" action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button class="form-submit">Submit</button>
        </form>
    </div>

    <div class="reg">
        <p> OR LOG IN <a href="{% url 'users:login' %}"><u>CLICKING HERE!</u></a></p>
    </div>
{% endblock %}