PPM_elaborato_backend/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name="homepage"),
    path('music/', include('music.urls')),
    path('users/', include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'music'

urlpatterns = [
    path('playlist/<int:playlist_id>/', views.playlist, name="playlist"),
    path('createPlaylist', views.createPlaylist, name='createPlaylist'),
    path('searchResults/', views.search_results, name="search_results"),
    path('allsongs/', views.all_songs, name="allsongs"),
    path('deletePlaylist', views.deletePlaylist, name="deletePlaylist"),
    path('addSongToPlaylist', views.addSongToPlaylist, name="addSongToPlaylist"),
    path('modify_playlist_image/<int:playlist_id>', views.modify_playlist_image, name='modify_playlist_image'),
    path('likedsongs/', views.likedsongs, name="likedsongs"),
    path('likesong', views.likesong, name="likesong"),
    path('add-song', views.add_song, name='add_song'),
    path('delete_song_from_playlist', views.delete_song_from_playlist, name="delete_song_from_playlist"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout', views.logout, name="logout"),
]

templates/homepage.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    PPMusic
{% endblock %}


{% block main-content %}
    <div id="All-songs" style="padding: 5px">
        <h2 class="home-tit"><a href="{% url 'music:allsongs' %}">All Songs</a></h2>
        {% if songs %}
            <p style="margin-left: 20px">There are {{ songs|length }} songs:</p>
        {% else %}
            <p style="margin-left: 20px">No songs found.</p>
        {% endif %}
        <div class="main-carousel" data-flickity='{"groupCells":5 , "contain": true, "pageDots": false, "draggable": false, "cellAlign": "left", "lazyLoad": true}'>
            {% for i in songs %}
                <div class="carousel-cell">
                    <section class="main_song">
                        <div class="song-card">
                            <div class="containera">
                                <img src="{{ i.image.url }}" id="A_{{i.song_id}}" alt="song cover">
                                <div class="overlaya"></div>
                                <div>
                                    <a class="play-btn" data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)"><i class="fas fa-play-circle fa-2x"></i></a>
                                    {% if user.is_authenticated %}
                                        <div class="add-playlist-btn">
                                            <a id="{{i.song_id}}" title="Add to Playlist" onclick="showDiv(this)"><i class="fas fa-ellipsis-h"></i></a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div>
                            <p class="songName" id="B_{{i.song_id}}"><a data-song-url="{{i.song.url}}" id="{{i.song_id}}" onclick="playSong(this)">{{i.name}}</a></p>
                            <p class="artistName" id="C_{{i.song_id}}">{{i.artist}}</p>
                        </div>
                    </section>
                </div>
            {% endfor %}
        </div>
    </div>

    {% if user.is_authenticated %}
    <h2 id="play-tit" class="home-tit">Your Playlists</h2>
    {% if my_playlists %}
            <p style="margin-left: 20px">You have {{ my_playlists|length }} playlists:</p>
        {% else %}
        <p style="margin-left: 20px">No playlists found. if you want to create a playlist <a onclick="document.getElementById('modal-wrapper-playlist').style.display='block'"><u>click here</u></a></p>
        {% endif %}
    <div class="main_content">
        {% for playlist in my_playlists %}
            <section class="main_song">
                <a href="{% url 'music:playlist' playlist.playlist_id %}"><img style="border-radius: 4%" src="{% if playlist.image %}{{ playlist.image.url }}{% else %}/media/images/music-placeholder.png{% endif %}" alt="playlist image"></a>
                <a class="playlist-title" href="{% url 'music:playlist' playlist.playlist_id %}">{{ playlist.playlist_name }}</a>
            </section>
        {% endfor %}
    </div>
    {% else %}
        <h2 id="play-tit" class="home-tit">Your Playlists</h2>
        <p style="margin-left: 20px">If you want to have your playlists <a href="{% url 'users:login' %}"><u>LOGIN HERE</u></a></p>
    {% endif %}
    
    <div id="divId">
        {% if my_playlists %}
            <label for="playlist_{{ song.song_id }}" style="margin: 5px; font-size: 0.75rem; font-weight: 700; color: rgb(138, 138, 138); text-align: left;">Add This Song To Your Playlist</label>
            <form style="margin:0;" id="my_form" action="{% url 'music:addSongToPlaylist' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="song_id" id="song_id">
                <select name="playlist_id" id="playlist_id">
                {% for playlist in my_playlists %}
                    <option value="{{playlist.playlist_id}}" class="left-panel-btn" style="margin:0;">{{playlist.playlist_name}}</option><br>
                {% endfor %}
                </select>
                <button class="submitb" type="submit">Add to Playlist</button>
            </form>
        {% else %}
            <p style="margin: 5px; font-size: 0.8rem; font-weight: 700; color: rgb(138, 138, 138); text-align: left;">You don't have any Playlist.</p>
            <a class="create-p" onclick="$('#divId').css({display: 'none'}); document.getElementById('modal-wrapper-playlist').style.display='block'"><i class="fas fa-plus"></i> Create Playlist</a>
        {% endif %}
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
{% endblock %}

templates/layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Layout page
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/flickity@2/dist/flickity.min.css">
    <script src="https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js"></script>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <script src="https://kit.fontawesome.com/e010442325.js" crossorigin="anonymous"></script>
    {% block head %}
    {% endblock %}
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <header>
        {% block header %}
        <nav id="header_menu">
            <a href="{% url 'homepage' %}" id="home-link">
                <p><img src="/media/images/home.png" width="30px" alt="home image">HOME</p>
            </a>
        {% if user.is_authenticated %}
            <div class="dropdown">
                <button class="btn btn-primary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="/media/images/headphones-2-48.png" width="30px">LIBRARY
                </button>
                <ul class="dropdown-menu" data-bs-theme="dark">
                    <li><a class="dropdown-item" href="{% url 'music:allsongs' %}">ALL SONGS</a></li>
                    <li><a class="dropdown-item" href="{% url 'homepage' %}#play-tit">YOUR PLAYLISTS</a></li>
                    <li><a class="dropdown-item" href="{% url 'music:likedsongs' %}">LIKED SONGS</a></li>
                    <li class="dropdown-divider"></li>
                    <li><a class="dropdown-item" onclick="document.getElementById('modal-wrapper-playlist').style.display='block'">+ CREATE A NEW PLAYLIST</a></li>
                    <li><a class="dropdown-item" onclick="document.getElementById('modal-wrapper-song').style.display='block'">+ ADD A NEW SONG TO DB</a></li>
                </ul>
        {% else %}
            <button class="btn btn-primary dropdown-toggle dropdown" id="librarybtn">
                <a href="{% url 'users:login' %}"><img src="../media/images/headphones-2-48.png" width="30px">LIBRARY</a>
            </button>
            
        {% endif %}
            </div>
            <h1><a href="{% url 'homepage' %}">PPMusic</a></h1>
            <form class="d-flex" role="search" autocomplete="off" method="POST" action="{% url 'music:search_results' %}"> 
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="Search Songs or Playlists" aria-label="Search" name="data" required>
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            {% if user.is_authenticated %}
                <div class="welcome">
                    <h4>Welcome, {{user.username}}!</h4>
                    <a href="users/logout">Log Out</a>
                </div>
            {% else %}
                <a href="{% url 'users:login' %}"><img src="/media/images/user_icon.png" class="icon"></a>
            {% endif %}
        </nav>
        {% endblock %}
    </header>

    <main>
    <div id='modal-wrapper-playlist' class='modal'>
        <form class='modal-content' action='{% url 'music:createPlaylist' %}' method="POST" enctype="multipart/form-data">{% csrf_token %}
            <h2>Create Playlist</h2>
            <div class='container'>
                <input id="playname-input" type='text' placeholder='Your New Playlist Name' name='playlist_name' required>
                <input type="file" name="image" accept="image/*">
                <br>
                <input id="submitb" type='submit' value="Create Playlist">
            </div>
        </form>
    </div>
    
    <div id='modal-wrapper-song' class='modal'>
        <form class='modal-content' action='{% url 'music:add_song' %}' method="POST" enctype="multipart/form-data">{% csrf_token %}
            <h2>Add a new Song to DataBase</h2>
            <div class='container'>
                <input type="text" name="name" placeholder="Song Name" required>
                <input type="text" name="artist" placeholder="Artist" required>
                <p style="margin: 0">Add music file:</p><input type="file" name="song" accept="audio/*" required>
                <br>
                <p style="margin: 0">Add image:</p><input type="file" name="image" accept="image/*">
                <br>
                <p style="margin: 0">Choose a genre:</p>
                <select name="genre" id="genre">
                    {% for value, display in genres %}
                        <option value="{{ value }}" {% if value == request.GET.genre %}selected{% endif %}>{{ display }}</option>
                    {% endfor %}
                </select>
                <br>
                <input id="submitb" type='submit' value="Add Song">
            </div>
        </form>
    </div>

    <div id="audio_main" class="audio-decs">
        <div class="audio-data">
            <div>
                <img id="audio-img" src="/media/images/music-placeholder.png" alt="Image here">
            </div>
            <div id="text-song">
                <h4 id="audio-song">Song Name</h4>
                <p id="audio-artist">Artist Name</p>
            </div>
        </div>
        <div style="margin: auto 0">
            <audio preload="auto" controls id="audioPlayer">
                <source src="" id="audioSource">
            </audio>
        </div>
    </div>

    {% block main-content %}
        
    {% endblock %}
    </main>

        <script>
            function new_playlist(){
                document.getElementById("modal-wrapper-playlist").style.display='block'}
            
            function new_song(){
                document.getElementById("modal-wrapper-song").style.display='block'}
            
            var modal_song = document.getElementById('modal-wrapper-song');
            var modal_playlist = document.getElementById('modal-wrapper-playlist');

            window.onclick = function (event) {
                if (event.target == modal_song) {
                modal_song.style.display = 'none';
            }
            if (event.target == modal_playlist) {
                modal_playlist.style.display = 'none';
            }
        }

            
            var play = true;
            var myAudio = document.getElementById("audioPlayer");
            function onKeyDown(event) {
                switch (event.keyCode) {
                    case 32: //SpaceBar
                        if (play) {
                            myAudio.pause();
                            play = false;
                        } else {
                            myAudio.play();
                            play = true;
                        }
                        break;
                }
                return false;
            }
            window.addEventListener("keydown", onKeyDown, false);
            
            function playSong(element){
            var songUrl = element.getAttribute('data-song-url');
            var audioPlayer = document.getElementById('audioPlayer');
            var audioSource = document.getElementById('audioSource');
            audioSource.src = songUrl;
            audioPlayer.load();
            audioPlayer.play();
            var songId = element.id;
            var newImage = document.getElementById("A_" + songId).src;
            var newSongName = document.getElementById("B_" + songId).textContent;
            var newArtistName = document.getElementById("C_" + songId).textContent;
            console.log(newSongName)
            console.log(newImage)
            console.log(newArtistName)

            document.getElementById("audio-img").src = newImage;
            document.getElementById("audio-song").textContent = newSongName;
            document.getElementById("audio-artist").textContent = newArtistName;
            }


            
        var song_id_for_playlist = document.getElementById("song_id");
        function showDiv(el) {
            var div = $("#divId");
            song_id_for_playlist.value = el.id;
            div.css({
                top: event.pageY,
                left: event.pageX,
                position: "absolute",
                display: "block"
            });

        }
        $(document).mouseup(function (e) {
            var container = $("#divId");
            if (!container.is(e.target) && container.has(e.target).length === 0) {
                container.fadeOut();
            }
        });

        function sendPostRequestPlaylistSong(el) {
            // alert("Song ID: "+song_id_for_playlist+" | Playlist ID: "+el.id);
            var data = song_id_for_playlist + "|" + el.id;
            $.ajax({
                "url": "{% url 'music:addSongToPlaylist' %}",
                "type": "POST",
                "data": { 'data': data, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                success: function(response) {
                alert("Song added to your playlist");
                location.reload();},
                error: function(xhr, status, error) {
                alert("Failed to add song to playlist.");}
                });
            var div = $("#divId");
            div.css({
                transition: "0.3s",
                display: "none"
            });
            
            
        function toggleHeart(element) {
            if (element.classList.contains('fa-regular')) {
                element.classList.remove('fa-regular');
                element.classList.add('fas', 'heart-red');
            } else {
                element.classList.remove('fas', 'heart-red');
                element.classList.add('fa-regular');
            }
        }
        }
        </script>
        {% block javascript %}
        {% endblock %}
    
    

</body>
</html>

templates/layout_users.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Layout page
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@200..700&display=swap" rel="stylesheet">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <header>
        {% block header %}
        <nav id="header_menu">
            <a href="{% url 'homepage' %}" id="home-link">
                <p><img src="/media/images/home.png" width="30px" alt="home image">HOME</p>
            </a>
            <h1><a href="{% url 'homepage' %}">PPMusic</a></h1>
        </nav>
        {% endblock %}
    </header>
    <main>
        {% block main-content %}
    	    Page content
        {% endblock %}
    </main>
</body>
</html>